### PR TITLE
OLE 121: Update for clarity and feedback from 2 brainstorming meetings.

### PR DESCRIPTION
**Pull request by msgilligan**
* Consistently use the word asset (not token or smart property)
* Add short Motivation content
* Clarify essential characteristics
* Enumerate 3 Transaction types, reserve 3 Omni Tx Type numbers
* Move 1-way conversion from Essential Characteristics to Limitations
* Add Issues and TODO

### CODE REVIEW

**Comment by msgilligan** [comment]
Updated and force-pushed with edits from today's meeting. I also changed the title and previous comment as appropriate.

**Review by marvgmail — CHANGES_REQUESTED** [review]
> In other words we need to define how many units of the UBA are represented by the satoshis in any given UTXO. This would be defined by the specification of the

We haven't decided that the satoshis will represent the number of units of the UBA in the UTXO. The amount might be represented fully in the OP_RETURN of the tx that created the UTXO. Also, the sentence, "This would be defined ..." isn't complete.

**Comment by msgilligan** [comment]
> > In other words we need to define how many units of the UBA are represented by the satoshis in any given UTXO.

> 
> We haven't decided that the satoshis will represent the number of units of the UBA in the UTXO. The amount might be represented fully in the OP_RETURN of the tx that created the UTXO. 

In this case the satoshis represent the amount fully-specified in the OP_RETURN. The language is pretty vague and I think vague enough to cover that option, as well.

I made a force-push to remove the dangling sentence.

**Comment by dexX7** [comment]
Looks good to me!

**Pull request merged**
